### ISSUE TITLE
touchscreen unresponsive

### ISSUE THREAD

**Issue by Cregs850** [tongueincheek/android_device_motorola_genevn#1]
after installing twrp on my device, touchscreen is unresponsive in twrp. how do i fix this?

**Comment by tongueincheek** [comment]
Try the updated build here:
[https://github.com/lexingtontezz/android_device_motorola_genevn/releases/tag/v0.1.1](https://github.com/lexingtontezz/android_device_motorola_genevn/releases/tag/v0.1.1)

I submitted for official status and this build passed their testing checklist. Let me know if it works for you. If not, then we might have different touch digitizers and I'll have to account for this in builds going forward. (Sometimes OEMs source multiple vendors for same-ish part during different production runs).

**Comment by Cregs850** [comment]
i just tried with the updated build and got the same result. touchscreen is unresponsive.

i used..

fastboot flash recovery_a twrp.img
fastboot flash recovery_b twrp.img

and i tried to just boot into twrp from fastboot and get an "no operating system found" error

**Comment by tongueincheek** [comment]
I'm willing to bet there is a difference in hardware here. Boot into bootloader and take note of the very bottom line. This tells you which touch panel you have. Mine says:

panel: 0x71650108 csot_nt36672c_660_1080x2400_dsc_vid_120hz

What is yours?

Also have you flashed vbmeta to remove AVB protection?

**Comment by tongueincheek** [comment]
https://github.com/lexingtontezz/android_device_motorola_genevn/commit/c8a487d

This commit fixes the issue for another user. Changes also pushed to official TWRP repo as well.
